### ISSUE TITLE
Bug S1 Unable to make booking in the near future

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#266]
Verified on Dev.

I've been testing booking and the appointment calendar. It seems that I cannot make bookings for the near future — within ~10 hours. (I haven't tested the boundaries so this is a guess.) The booking preferences for the provider are: book any time, with no limit to how soon items can be booked. 

I'm at UTC-8.

Here's the exception I get when trying to book on the booking confirmation screen:

Object reference not set to an instance of an object.

```
Technical details: {"errorMessage":"Object reference not set to an instance of an object.","exception":{"ClassName":"System.NullReferenceException","Message":"Object reference not set to an instance of an object.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":" at CalendarDll.ProviderAvailability..ctor(DataContainer obj) in C:\\Users\\Iago\\Proxectos\\Loconomics\\code\\iCalendarLib\\CalendarDll\\DbUtilsTypes.cs:line 100
 at CalendarDll.CalendarUtils.<GetFreeEvents>b__1(DataContainer dts) in C:\\Users\\Iago\\Proxectos\\Loconomics\\code\\iCalendarLib\\CalendarDll\\CalendarUtils.cs:line 277
 at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
 at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
 at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
 at CalendarDll.CalendarUtils.GetFreeEvents(CalendarUser user, DateTimeOffset startDate, DateTimeOffset endDate, DateTimeOffset currentDateTimeForAdvanceTime) in C:\\Users\\Iago\\Proxectos\\Loconomics\\code\\iCalendarLib\\CalendarDll\\CalendarUtils.cs:line 276
 at LcCalendar.GetUserAvailability(Int32 userID, DateTimeOffset dateStart, DateTimeOffset dateEnd, Boolean excludeAdvanceTime)
 at LcCalendar.CheckUserAvailability(Int32 userID, DateTimeOffset dateStart, DateTimeOffset dateEnd, Boolean excludeAdvanceTime)
 at LcRest.Booking.CheckAvailability(DateTimeOffset startTime, Nullable`1 serviceDurationMinutes, Int32 serviceProfessionalUserID, String timeZone)
 at LcRest.Booking.InsClientBooking(Int32 clientUserID, Int32 serviceProfessionalUserID, Int32 jobTitleID, Address serviceAddress, DateTimeOffset serviceStartTime, Nullable`1 alternative1StartTime, Nullable`1 alternative2StartTime, IEnumerable`1 services, Int32 languageID, Int32 countryID, String bookCode, String specialRequests)
 at ASP._Page_api_v1_me_client_booking_cshtml.RestMeClientBooking.CreateItem()
 at ASP._Page_api_v1_me_client_booking_cshtml.RestMeClientBooking.Post()
 at RestWebPage.Run(WebPage WebPage)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"1\n.ctor\nCalendarDll, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null\nCalendarDll.ProviderAvailability\nVoid .ctor(CalendarDll.DataContainer)","HResult":-2147467261,"Source":"CalendarDll","WatsonBuckets":null}}
```

**Comment by IagoSRL** [comment]
I found the specific cause of problem, and was about checking availability at a time frame that has two events with a different availability than 'busy'. Because the 'busy occurrence' object was null (since no busy events in that time), the reference error was triggered.

The problem happened at DbUtilsTypes.cs:line 100 but could have happened on lines 101 and 102 depending on the availability type of the events and only if two or more happened on the same time frame with a lower availability priority than 'busy'.

The bug usually would have arise when checking availability for a time that has a tentative event (as generated by a non still confirmed booking request), because one tentative and one free event happens at same time, and checking busy thrown exception.

With small changes and a single commit the bug is fixed; do some more testing if you want but since is clearly identified and tested I'm sure is fixed and that's why I left it as 'closed by the commit'.
