### ISSUE TITLE
Calendar error when using 'all days/times available'

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#865]
### Long Description
As found by @samwa and commented by email and Slack, the calendar in the app is throwing error on some cases.
After some research, we found that the error is triggered when choosing an availability of 'all days/times' at weekly schedule.

*Please @samwa, if you found this error still happening with a different set-up than that preference, let me know.*

### Exception details
```
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=CalendarDll
  StackTrace:
       at CalendarDll.CalendarUtils.<GetEventsOccurrencesInAvailabilitySlotsUtc>d__25.MoveNext() in D:\Iago\Proxectos\Loconomics\code\iCalendarLib\CalendarDll\CalendarUtils.cs:line 1360
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
       at LcCalendar.GetAvailability.<OccurrencesWithAdvanceTimeSlot>d__d7.MoveNext() in c:\Projects\Github\samwa-loconomics\loconomics\web\App_Code\LcCalendar.GetAvailability.cs:line 195
       at LcCalendar.GetAvailability.<FilterEndTimeOccurrences>d__cf.MoveNext() in c:\Projects\Github\samwa-loconomics\loconomics\web\App_Code\LcCalendar.GetAvailability.cs:line 136
       at LcCalendar.GetAvailability.<GetTimeline>d__ec.MoveNext() in c:\Projects\Github\samwa-loconomics\loconomics\web\App_Code\LcCalendar.GetAvailability.cs:line 361
       at LcCalendar.GetAvailability.<OptimizeTimeline>d__fc.MoveNext() in c:\Projects\Github\samwa-loconomics\loconomics\web\App_Code\LcCalendar.GetAvailability.cs:line 522
       at LcCalendar.GetAvailability.<GetTimelinePublicOutputFormat>d__e0.MoveNext() in c:\Projects\Github\samwa-loconomics\loconomics\web\App_Code\LcCalendar.GetAvailability.cs:line 287
       at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) in c:\Development\Releases\Json\Working\Newtonsoft.Json\Src\Newtonsoft.Json\Serialization\JsonSerializerInternalWriter.cs:line 589
       at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) in c:\Development\Releases\Json\Working\Newtonsoft.Json\Src\Newtonsoft.Json\Serialization\JsonSerializerInternalWriter.cs:line 933
```
### Exception source
It happens that iCal.Net is not assigning an AssociatedObject on that cases, and that's the property that throws an 'Object reference not set to an instance of an object' error.
Looks like could be related to the event having a value of true (1) at the IsAllDay column, but when choosing a single week day with full availability the error is not throw (maybe is not tagged properly as IsAllDay, though); or maybe is related with recurrent events calculations, like not assigning an object on generated occurrences.

### Aside notes
The affected preference worked in the past with no problems.
Recently, some fixes to mitigate iCal.Net bugs with managing timezone times conversion were added, maybe that code is accessing the AssociatedObject without check for null value.
Every event must match and associated object, but I'm not sure about recurrent occurrences

**Comment by IagoSRL** [comment]
Issue #874 was actually duplicated of this, fixed and released, so closing.
